### Health Check
GET http://localhost:3000/health


#### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "vscode1@test.com",
  "password": "pass123"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}




### Replace token
# user token
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNDNjZDExZi02MDExLTRkMWMtYmIwOC0wMDAwMjAzNDRmMmIiLCJzZXNzaW9uSWQiOiIzYWZkNzdmOS1mYWQ1LTRlYzgtODYxNC00MTQ2YTQxMWZmZDkiLCJpYXQiOjE3Njc2ODM0NzksImV4cCI6MTc2Nzc2OTg3OX0.520mOOU_BzQaRS-uQM1Nhia4sK1y4Tcu1VjpH6KG4p4

# admin token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NmVjMmUyZi1hN2QxLTRkMjgtOGZjNy1iY2IzNzQ3YTRlM2IiLCJzZXNzaW9uSWQiOiJjNTJjNmFmNi05MzZlLTRmZjYtOTE5Zi0zNjJjYjA1YjZjNzciLCJpYXQiOjE3Njc2OTg1NjcsImV4cCI6MTc2Nzc4NDk2N30.hVeTRaVGGDX0fexNuiILioX6FTVwfF1VPVBseykH64k

### Create Quote
POST http://localhost:3000/quotes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pair": "INRUSD",
  "side": "BUY",
  "amount": 100
}

### Replace Quoteid
@quoteid = 5d47efa4-1834-4339-b3bb-0fe7ac979360
### Execute Self Trade
POST http://localhost:3000/trades/self
Authorization: Bearer {{token}}
Idempotency-Key: {{quoteid}}
Content-Type: application/json

{
  "quoteId": "{{quoteid}}",
  "amount": 10
}

### Execute Other Trade
# UserIds
# @user = 64626faf-0bfd-493e-b830-3ec800e23344 
# @user = a3d7e3f3-ae0b-4a3d-b6dc-54e32d0fa59d 
# @user = e66d3ab6-ecd5-4fe7-971a-4ebeba459f5c 
 @user = 343cd11f-6011-4d1c-bb08-000020344f2b 

# @reciever = 64626faf-0bfd-493e-b830-3ec800e23344 
# @reciever = a3d7e3f3-ae0b-4a3d-b6dc-54e32d0fa59d 
@reciever = 56ec2e2f-a7d1-4d28-8fc7-bcb3747a4e3b
#@reciever = bf6eed57-36b7-434e-a22d-a88291d52bff 

POST http://localhost:3000/trades/others
Authorization: Bearer {{token}}
Idempotency-key: {{quoteid}}
Content-Type: application/application/json

{
  "quoteId": "{{quoteid}}",
  "amount": 10,
  "receiverId": "{{reciever}}"
}

### Get Balances
GET http://localhost:3000/balances
Authorization: Bearer {{token}}

### Add Credits

POST http://localhost:3000/dev/addMoney
Authorization: Bearer {{token}}

{
  "currency": "USD",
  "amount": 100,
  "reciverId": "{{user}}"
}

### Get history
GET http://localhost:3000/history
Authorization: Bearer {{token}}
