export const ErrorCode = {
  NO_PERMISSION: "NO_PERMISSION",
  NOT_FOUND: "NOT_FOUND",
  INVALID_INPUT: "INVALID_INPUT",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS", 
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  MARKET_PRICE_UNAVAILABLE: "MARKET_PRICE_UNAVAILABLE",
  INVALID_QUOTE:"INVALID_QUOTE",
  QUOTE_EXPIRED:"QUOTE_EXPIRED",
  DUPLICATE_TRADE: "DUPLICATE_TRADE",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
 